name: Build Wechat and Push Multi-arch Docker Image

# 定义触发条件，比如代码推送到main分支时触发
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天的00:00触发
# 定义工作流中的作业
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 设置环境变量
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/docker-wechat
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    # 定义作业中的步骤
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置Docker构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 构建Docker镜像（支持多平台）并推送到DockerHub，同时打上日期标签
      - name: Build and push Docker image with tags
        run: |
          DATE_TAG=$(date +'%Y%m%d')
          docker buildx build --platform linux/amd64,linux/arm64 \
            --file Dockerfile-wechat \
            -t $IMAGE_NAME \
            -t $IMAGE_NAME:$DATE_TAG \
            . --push
