name: Build and Push Multi-arch Docker Image

# 定义触发条件，比如代码推送到main分支时触发
on:
  workflow_dispatch:
# 定义工作流中的作业
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 设置环境变量
    env:
      IMAGE_NAME: smanx/docker-wechat
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    # 定义作业中的步骤
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置Docker构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 构建Docker镜像（支持多平台）并推送到DockerHub
      - name: Build and push Docker image for multiple platforms
        run: docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME . --push

      # 为镜像打上年月日的标签并再次推送
      - name: Tag and push Docker image with date
        run: |
          DATE_TAG=$(date +'%Y%m%d')
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:$DATE_TAG . --push

      # 推送Docker镜像到DockerHub（此步骤实际上在上面的构建命令中已经包含）
      # - name: Push Docker image
      #   run: docker push $IMAGE_NAME